### PR TITLE
Opf integration

### PR DESCRIPTION
**Pull request by mrbaseman**
This is a backport of a couple of features from the 2.x-dev branch:

In the 2.x-dev Branch we have started to replace the classical output_filter module by the OpF Dashboard module, which 
- allows much more fine grained control which filters are applied to which page,
- allows to create filters that are applied to specific modules only
- contains an own mechanism to import/export filters, but also supports WB(CE) modules being a filter
- allows creating and testing filters on the fly directly in the backend
- ...and many more nice features all around postprocessing the output just before it is sent to the client

All classical output filters are turned into individual (filter-)modules. 
The classical output_filter module is uninstalled during update, but there is a legacy module "opf_simple_backend" shipped together with this pull request, which makes the OpF Dashboard backend look like the classical output_filter admin tools module. However, behind the curtains, the new mechanism for applying filters is used. You can switch between classical (basic) and advanced view.

All filters are based on the current 1.3.2 branch (the ones in the 2.x-dev branch were a bit outdated when I have started to backport this part of the development).  And, BTW during upgrade, the filter settings are preserved, because the new filter modules use the same settings as the classical output_filters. 

Together with the filters, also the support for hidden modules (opf_simple_backend is one) is backported. Hidden modules are admintools not shown in the list of admintools because they are used from another module as some kind of extension. There is also a mechanism that blocks core modules from being uninstalled but to my impression this feature has already been backported.

There is another interesting feature for developers: With the new filter mechanism it is possible to apply filters to the backend. This is currently disabled by default, but it might be interesting for future backend templates.

### CODE REVIEW

**Comment by Colinax** [comment]
Hi mrbaseman,

I looked at your PR.
In the Advanced Options the following two warnings are displayed several times:

Warning:  count(): Parameter must be an array or an object that implements Countable in C:\xampp\htdocs\modules\outputfilter_dashboard\functions.php on line 178  
Warning:  count(): Parameter must be an array or an object that implements Countable in C:\xampp\htdocs\modules\outputfilter_dashboard\functions.php on line 181

Installed php version is 7.2.8

What is the difference between the Admin-Tools OPF E-Mail and Output Filter Dashboard, as the functions of the "OPF Email" already exist in the Output Filter Dashboard?

**Comment by mrbaseman** [comment]
I have tested with php 7.0 so far. I'll create a testing environment with php 7.2 and fix those warnings.

The OPF E-Mail is a filter module that (apart from being switched on/off) has its own settings (at-replacement, dot-replacement, and how email addresses shall be replaced (email addresses, mailto links, and if JS shall be used). From the advanced view of the dashboard there is a link to this backend tool in the list of the filters. In the basic configuration view, the same settings are available, too. 
Well, it's because users are used to find them there. I can think of a simple solution: Remove the options concerning email from the opf_simple_backend, and maybe put a link there, which directs the user to the OPF Email tool.
The other solution would be to make "OPF Email" a hidden module, but then the link to the filter settings in the advanced view of the dashboard stops working, because it simply calls that admintool. For a hidden module the dashboard itself is responsible for including the tool.php...  just like it works with the opf_simple_backend. For arbitrary filter modules, however, I think a bit more validation is needed, because the module's url is retrieved via http-get, so some filtering and plausibility tests against the database is probably needed. Probably this doesn't require too much effort either. I'll check both options.

**Comment by mrbaseman** [comment]
I have made the code php 7.2 ready. 
For the Email filter configuration I have decided to keep it in the mod_opf_email tool and keep that one visible in the list of admin tools. I have removed the redundant Email settings from opf_simple_backend and added a link to mod_opf_email instead.
I have also tried to call it from the dashboard and keep it hidden. However, to make this working reliably, I would have to copy larger parts from admin/admintools/tool.php (set up the toolDir, perform a modified toolCheck, load the language files... whereas with a tool that is not hidden I just can rely on the existing functions of the core for the admintools.

**Comment by mrbaseman** [comment]
I have noticed that the opf_simple_backend occasionally gets activated by mistake, e.g. when moving filters via drag&drop. I'll look into this problem and commit a fix for it.

**Comment by mrbaseman** [comment]
I have [fixed](https://github.com/WBCE/WBCE_CMS/pull/345/commits/d62ed87f3b99901242de69cb9fc214e6bf746e7e) the [above-mentioned](https://github.com/WBCE/WBCE_CMS/pull/345#issuecomment-426237059) issue.

When working on an output filter for #344 I have found another issue related to phplib, which I have [solved](https://github.com/WBCE/WBCE_CMS/pull/345/commits/a100290002023132b7f206125ceaaa5178591e0b), too.
For the interested reader: Each time when set_block is used, the source of this block is wiped out from the original template. So, you can re-use blocks, but you may not switch to a different block meanwhile. Since the various field types are implemented as different blocks, it is necessary to restore the template after each parser iteration, so that subsequent occurrences of the same field type have the appropriate block still available in the template.

**Comment by mrbaseman** [comment]
with the past few commits I have addressed the issues discussed in the forum, but now I have noticed that the dashboard (up to now) decides depending on the existence of the class Tool if backend filtering is supported or not (probably because that was one of the other innovations in the 2.x-dev branch). What other feature could I use for this? I could simply grep for 'opf_controller' in the source for the admin class. But is there a more elegant solution?

**Comment by mrbaseman** [comment]
I have just found the answer to my previous question: The necessary call was already included in [1.3.0](https://github.com/WBCE/WBCE_CMS/blob/1.3.0/wbce/framework/class.admin.php#L235) - so I can do a simple `version_compare(WBCE_VERSION, '1.3.0', '>=)`

**Comment by mrbaseman** [comment]
well, it seems not to be that easy as I thought, because for instance backend-Modules don't exist (yet?) like in the 2.x-dev branch. So for some aspects the existence of the "Tool" class might still be a good indicator, whereas the version_compare is more appropriate in other places.
Also I have noticed that the Settings for the backend sometimes are changed by mistake by the dashboard. So, I'll further look into these issues

**Comment by mrbaseman** [comment]
This PR has become quite lengthy. I'd suggest that we squash all the commits before or during merge, once we have a final version. 
I have just fixed the issue mentioned in the previous comment, but still, backend filtering doesn't work as expected yet.

**Comment by mrbaseman** [comment]
I have added the support for the insert class in mod_opf_auto_placeholders and rebased and squashed all the commits now.

**Comment by mrbaseman** [comment]
I have merged the latest changes to the Auto Placeholders filter from 1.3.2 and squashed the commits again. If the insert class is available, those changes are obsolete anyway, but if for some reason the class auto loader doesn't work, the conventional insert rules within the filter module provide a fallback.

**Pull request merged**
